package com.mizhousoft.apple.open.service;

import com.mizhousoft.apple.open.result.AppleVerifyResult;
import com.mizhousoft.apple.open.service.impl.JWKAuthenticationServiceImpl;
import com.mizhousoft.commons.restclient.TruststoreLoader;
import com.mizhousoft.commons.restclient.service.impl.HttpsRestClientServiceImpl;

/**
 * JWKAuthenticationServiceImpl Test
 *
 * @version
 */
public class JWKAuthenticationServiceImplTest
{
	public static void main(String[] args) throws Exception
	{
		HttpsTruststoreLoader truststoreLoader = new HttpsTruststoreLoader();
		truststoreLoader.loadTrustStore();

		TruststoreLoader[] truststoreLoaders = { truststoreLoader };

		HttpsRestClientServiceImpl restClientService = new HttpsRestClientServiceImpl();
		restClientService.setTruststoreLoaders(truststoreLoaders);
		restClientService.init();

		JWKAuthenticationServiceImpl jwkAuthenticationService = new JWKAuthenticationServiceImpl();
		jwkAuthenticationService.setRestClientService(restClientService);

		String audience = "com.usmartcloud.repair.production";

		String identityToken = "ZXlKcmFXUWlPaUk0TmtRNE9FdG1JaXdpWVd4bklqb2lVbE15TlRZaWZRLmV5SnBjM01pT2lKb2RIUndjem92TDJGd2NHeGxhV1F1WVhCd2JHVXVZMjl0SWl3aVlYVmtJam9pWTI5dExuVnpiV0Z5ZEdOc2IzVmtMbkpsY0dGcGNpNXdjbTlrZFdOMGFXOXVJaXdpWlhod0lqb3hOVGcyTVRZeE1qQTJMQ0pwWVhRaU9qRTFPRFl4TmpBMk1EWXNJbk4xWWlJNklqQXdNRGt5Tnk0Mk1UVXpNV1JtWldObU1tVTBaV1E0WW1GbU9EUmpOVEJoTlRNMk1qWmxZUzR3T1RVMklpd2lZMTlvWVhOb0lqb2lXbDlxUVU5VlJGVkdhRU5ZTTBwclQxVkZNaTFzUVNJc0ltVnRZV2xzSWpvaWJITndYMnhwYzJoMWFYQnBibWRBY1doelpXVnlMbU52YlNJc0ltVnRZV2xzWDNabGNtbG1hV1ZrSWpvaWRISjFaU0lzSW1GMWRHaGZkR2x0WlNJNk1UVTROakUyTURZd05pd2libTl1WTJWZmMzVndjRzl5ZEdWa0lqcDBjblZsZlEuU1lQS3BSdVZNbFhTQlhYZDFSNXkwQ2t4Q2pVYXRaQjEwTjBkd0dsNnJSWUo5cl9zYkFnMHlzOEVmZEpJcU44NktCMEpXX2wzNXVMdjR1TlIyVGpwUFdreF9EMUl3VVpWd25RUDVsTjBPVUJCbzNlVkZTcDZHSUtXS0NLMHBSZDJUak00Z0d2U043ZHBJZ1lnajFabWNuZlIxS3VMYk56QlRvZUJ6cXdhZDQ3OWpIak85ZUx1OVp6X1o4WG1JNVJfRFdpLV9weXdwY3YwcGFpVzlvU1BveW5hNzU1ZjgwTDRoekVxRjRHMzFTempfT3ZucDlOb0lzbW5LdDUzMlBjQXZuTUpJQmpNZkhJZGJoUE9ld1l6MmFrR1prTnRiX2xIVmtneFNIblp3ZXU5bE5hOXE5b3B1bk5XclR0VFlFa09aaUpJMGg3ZEkzbm9xWGhzcFVaa2pB";
		String subject = "000927.61531dfecf2e4ed8baf84c50a53626ea.0956";
		AppleVerifyResult result = jwkAuthenticationService.verify(audience, subject, identityToken);
		System.out.println(result.toString());

		identityToken = "ZXlKcmFXUWlPaUpsV0dGMWJtMU1JaXdpWVd4bklqb2lVbE15TlRZaWZRLmV5SnBjM01pT2lKb2RIUndjem92TDJGd2NHeGxhV1F1WVhCd2JHVXVZMjl0SWl3aVlYVmtJam9pWTI5dExuVnpiV0Z5ZEdOc2IzVmtMbkpsY0dGcGNpNXdjbTlrZFdOMGFXOXVJaXdpWlhod0lqb3hOVGcyTVRZeE1qTXhMQ0pwWVhRaU9qRTFPRFl4TmpBMk16RXNJbk4xWWlJNklqQXdNRGt5Tnk0Mk1UVXpNV1JtWldObU1tVTBaV1E0WW1GbU9EUmpOVEJoTlRNMk1qWmxZUzR3T1RVMklpd2lZMTlvWVhOb0lqb2liMnh3YzBsSmRsRXpTbmRtVlUxVmJscGpia0ZWWnlJc0ltVnRZV2xzSWpvaWJITndYMnhwYzJoMWFYQnBibWRBY1doelpXVnlMbU52YlNJc0ltVnRZV2xzWDNabGNtbG1hV1ZrSWpvaWRISjFaU0lzSW1GMWRHaGZkR2x0WlNJNk1UVTROakUyTURZek1Td2libTl1WTJWZmMzVndjRzl5ZEdWa0lqcDBjblZsZlEueXZGbWpCUXVDd1FsWTNTeDlmZnZNZ0lyUDRmT1JncllXV2w2SDFqZnY4NGM1WlhiQlppdk92M3gzZDZyUnA4bmlQNEgxeURnTHBHRjZUT0kwSDU1MHJuc283M095WnNlT2FpamltTXQ4Z1g5bGFsOHRfY2huMlNoTW9IbkUzbUtOeHA0dThCZGdXZEUyUVJMd2laZUZ3M3NuVXA1SmNRc0RnU21pQ0s3M18zQXdzbU1mc0xBTHVEZDFFNUk4NHlKWkNQQ2RGR19tRUZPOFpjLUY4QjNyRWdwdTF4NHk2YXBjRUV3MWNHbkNjSlppRmVObVZCTC1yQmhpcE5vXzBTenNOWnlRdHNCZEFMZ0FaVEZmQkxDb0ZoOHA0UkRZVUtVUjVKbUdkUjh1TWE0UVk5Sy1nTTF1NWNfNTltWEQzOFk1aEJZUmZWbG80WTNnWkNJTWVxam5R";
		subject = "000927.61531dfecf2e4ed8baf84c50a53626ea.0956";
		result = jwkAuthenticationService.verify(audience, subject, identityToken);
		System.out.println(result.toString());
	}
}
